config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :premium_subscriptions do
    get :xlsdata, on: :collection
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/premium_subscription.rb
class PremiumSubscription < ApplicationRecord
  belongs_to :user

  enum shirt_size: [:S, :M, :L, :XL, :XXL]
  enum subscription_length: [:one_week, :one_month, :one_year]

  def self.query_results(params)
    max_entries = params[:max_entries].to_i if params[:max_entries].present?
    start_date  = DateTime.new(params[:start_date][:year].to_i, params[:start_date][:month].to_i, params[:start_date][:day].to_i) if
        params[:start_date] && params[:start_date] && params[:start_date][:year].present? && params[:start_date][:month].present? && params[:start_date][:day].present?
    end_date    = DateTime.new(params[:end_date][:year].to_i, params[:end_date][:month].to_i, params[:end_date][:day].to_i) if
        params[:end_date] && params[:end_date] && params[:end_date][:year].present? && params[:end_date][:month].present? && params[:end_date][:day].present?
    end_date ||= start_date # only end date assignment is not allowed

    sorting     = params[:sort_by].present? ? params[:sort_by] : 'created_at'

    query = PremiumSubscription.order("#{sorting} DESC")
    query = query.where('created_at BETWEEN ? AND ?', start_date.beginning_of_day, end_date.end_of_day) if start_date
    query = query.limit(max_entries) if max_entries

    return query
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :premium_subscriptions, dependent: :destroy

  validates :first_name, :last_name, presence: true, allow_blank: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/premium_subscriptions_controller.rb
class PremiumSubscriptionsController < ApplicationController
  before_action :set_premium_subscription, only: [:show, :edit, :update, :destroy]
  before_action :store_xlsdata_requests, only: [:xlsdata]

  # GET /premium_subscriptions
  # GET /premium_subscriptions.json
  def index
    @premium_subscriptions = PremiumSubscription.all
  end

  # GET /premium_subscriptions/1
  # GET /premium_subscriptions/1.json
  def show
  end

  # GET /premium_subscriptions/new
  def new
    @premium_subscription = PremiumSubscription.new
  end

  # GET /premium_subscriptions/1/edit
  def edit
  end

  # GET /premium_subscriptions/xlsdata
  def xlsdata
    if request.format.xlsx?
      @premium_subscriptions = PremiumSubscription.query_results(params)
      render :status => 404 unless @premium_subscriptions.any?
    end

    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename="subscription_report.xlsx"'
      }
    end
  end

  # POST /premium_subscriptions
  # POST /premium_subscriptions.json
  def create
    @premium_subscription = PremiumSubscription.new(premium_subscription_params)

    respond_to do |format|
      if @premium_subscription.save
        format.html { redirect_to @premium_subscription, notice: 'Premium subscription was successfully created.' }
        format.json { render :show, status: :created, location: @premium_subscription }
      else
        format.html { render :new }
        format.json { render json: @premium_subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /premium_subscriptions/1
  # PATCH/PUT /premium_subscriptions/1.json
  def update
    respond_to do |format|
      if @premium_subscription.update(premium_subscription_params)
        format.html { redirect_to @premium_subscription, notice: 'Premium subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @premium_subscription }
      else
        format.html { render :edit }
        format.json { render json: @premium_subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /premium_subscriptions/1
  # DELETE /premium_subscriptions/1.json
  def destroy
    @premium_subscription.destroy
    respond_to do |format|
      format.html { redirect_to premium_subscriptions_url, notice: 'Premium subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_premium_subscription
      @premium_subscription = PremiumSubscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def premium_subscription_params
      params.require(:premium_subscription).permit(:shirt_size, :user_id, :subscription_length, :shipped, :shipping_address)
    end

    # Store the number of requests to the XLS decode in REDIS
    def store_xlsdata_requests
      #TODO Add redis.incr "xlsdata_count"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/premium_subscriptions_helper.rb
module PremiumSubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NpsTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/premium_subscriptions/_form.html.erb
<%= form_for(premium_subscription) do |f| %>
    <% if premium_subscription.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(premium_subscription.errors.count, "error") %> prohibited this premium_subscription from being saved:</h2>

          <ul>
            <% premium_subscription.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :shirt_size %>
      <%= f.select :shirt_size, PremiumSubscription.shirt_sizes.keys %>
    </div>

    <div class="field">
      <%= f.label :user_id %>
      <%= f.number_field :user_id %>
    </div>

    <div class="field">
      <%= f.label :subscription_length %>
      <%= f.select :subscription_length, PremiumSubscription.subscription_lengths.keys %>
    </div>

    <div class="field">
      <%= f.label :shipped %>
      <%= f.check_box :shipped %>
    </div>

    <div class="field">
      <%= f.label :shipping_address %>
      <%= f.text_field :shipping_address %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/premium_subscriptions/edit.html.erb
<h1>Editing Premium Subscription</h1>

<%= render 'form', premium_subscription: @premium_subscription %>

<%= link_to 'Show', @premium_subscription %> |
<%= link_to 'Back', premium_subscriptions_path %>

app/views/premium_subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Premium Subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Shirt size</th>
      <th>User</th>
      <th>Subscription length</th>
      <th>Shipped</th>
      <th>Shipping address</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @premium_subscriptions.each do |premium_subscription| %>
      <tr>
        <td><%= premium_subscription.shirt_size %></td>
        <td><%= premium_subscription.user_id %></td>
        <td><%= premium_subscription.subscription_length.humanize %></td>
        <td><%= premium_subscription.shipped %></td>
        <td><%= premium_subscription.shipping_address %></td>
        <td><%= premium_subscription.created_at %></td>
        <td><%= link_to 'Show', premium_subscription %></td>
        <td><%= link_to 'Edit', edit_premium_subscription_path(premium_subscription) %></td>
        <td><%= link_to 'Destroy', premium_subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Users', users_path %> |
<%= link_to 'New Premium Subscription', new_premium_subscription_path %> |
<%= link_to 'XLS Data Export', xlsdata_premium_subscriptions_path %>

app/views/premium_subscriptions/new.html.erb
<h1>New Premium Subscription</h1>

<%= render 'form', premium_subscription: @premium_subscription %>

<%= link_to 'Back', premium_subscriptions_path %>

app/views/premium_subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shirt size:</strong>
  <%= @premium_subscription.shirt_size %>
</p>

<p>
  <strong>User:</strong>
  <%= @premium_subscription.user_id %>
</p>

<p>
  <strong>Subscription length:</strong>
  <%= @premium_subscription.subscription_length.humanize %>
</p>

<p>
  <strong>Shipped:</strong>
  <%= @premium_subscription.shipped %>
</p>

<p>
  <strong>Shipping address:</strong>
  <%= @premium_subscription.shipping_address %>
</p>

<%= link_to 'Edit', edit_premium_subscription_path(@premium_subscription) %> |
<%= link_to 'Back', premium_subscriptions_path %>

app/views/premium_subscriptions/xlsdata.html.erb
<h1>Premium Subscriptions Query</h1>

<%= form_tag(xlsdata_premium_subscriptions_path(format: :xlsx), method: 'get') do %>
    <%= label_tag(:start_date, "Start Date:") %>
    <%= select_date nil, prefix: :start_date, include_blank: true %>
    <%= label_tag(:end_date, "End Date:") %>
    <%= select_date nil, prefix: :end_date, include_blank: true %>
    <%= label_tag(:max_entries, "Max Entries:") %>
    <%= number_field_tag :max_entries, 20  %>
    <br>
    <%= radio_button_tag(:sort_by, "created_at", checked: true) %>
    <%= label_tag(:sort_date, "Sort By Date") %>
    <%= radio_button_tag(:sort_by, "shirt_size") %>
    <%= label_tag(:sort_shirt, "Sort By Shirt Size") %>
    <br>
    <%= submit_tag("Search") %>
<% end %>

<%= link_to 'Users', users_path %> |
<%= link_to 'Premium Subscriptions', premium_subscriptions_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %> |
<%= link_to 'Premium Subscriptions', premium_subscriptions_path %> |
<%= link_to 'XLS Data Export', xlsdata_premium_subscriptions_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @user.id %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>